name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # 1) Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3) Cache node_modules
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # 4) Install deps
      - name: Install dependencies
        run: npm ci

      # 5) Type check
      - name: Type check
        run: npm run typecheck

      # 6) Build (electron-vite)
      - name: Build
        run: |
          npm run build:mcp
          npm run build

      # 7) Unit tests
      - name: Unit tests
        run: npm run test:unit

      # 8) E2E tests
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: E2E tests
        run: npm run test:e2e

      # 9) Upload coverage (optional)
      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info